version: '3.8'

services:
  skullking-front:
    image: node:18-alpine
    container_name: skullking-front
    working_dir: /app
    ports:
      - ${APP_PORT:-3000}:3000
    volumes:
      - ./:/app
    command: ['node', '/app/build/index.js']
